### ISSUE TITLE
Error when only using `fp-ts`, not `io-ts`

### ISSUE THREAD

**Issue by svdo** [relmify/jest-fp-ts#3]
Hi! Thanks for creating this library, it is a lot more extensive than my `fp-ts-jest-matchers`, so I plan to phase that out and point people over to here.

I did run into one issue however: my project only uses `fp-ts` as a dependency, not `io-ts`. It appears however that this library requires `io-ts` to also be present, because I get this error:

```
Test suite failed to run

    Cannot find module 'io-ts' from 'isEither.js'

    However, Jest was able to find:
        './isEither.d.ts'
        './isEither.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
        './toBeEither.d.ts'
        './toBeEither.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
```

That's a lot of partially confusing output, but I think the important bit is `Cannot find module 'io-ts' from 'isEither.js'`.

**Comment by leilapearson** [comment]
Hi @svdo, 

Thanks for the issue report. Glad you're finding it to be useful!

I listed `io-ts` as a peer dependency in the `package.json`. Hopefully it gave you a warning that it was required when you installed the package?

You can see a long explanation for why I'm using `io-ts` for `isEither()`  here:https://github.com/gcanti/fp-ts/issues/1168#issuecomment-602054319

Besides that matcher, I also rely on `io-ts` for `toBeLeftWithErrorsMatching(value)` which is quite tied to `io-ts`.  

I did manage to avoid a dependency on `io-ts-types` by copying in just the small amount of code I needed.

I see that I missed mentioning these peer dependencies in the README. I've updated it now and will include that in my next update.

Will that resolve your issue? Or did you have any particular concerns about adding `io-ts` as a dev dependency in your project?  

-Leila

**Comment by svdo** [comment]
I can see where you're coming from. I do sometimes get nightmares because of the amount of dependencies in JS/TS projects, and the resulting security issues all over the place. So in general I always try to minimise the number of dependencies. Having said that, in this case the number of additional dependencies introduced by `io-ts` is probably low if you already have `fp-ts` (I didn't verify that), and they are only dev dependencies, so I guess I'm OK with that choice. Thanks for your explanation!

**Comment by leilapearson** [comment]
Great and thanks again!
