### ISSUE TITLE
Installation instructions do not work (simple repository included)

### ISSUE THREAD

**Issue by JVMartin** [relmify/jest-fp-ts#6]
I've created a repository attempting to use this package here, following your instructions to a T:
https://github.com/JVMartin/jest-fp-ts-broken

Note I've included the package:
https://github.com/JVMartin/jest-fp-ts-broken/blob/master/package.json#L46

Added it to Jest config:
https://github.com/JVMartin/jest-fp-ts-broken/blob/master/jest.config.js#L6

Added it to global:
https://github.com/JVMartin/jest-fp-ts-broken/blob/master/global.d.ts

Included global:
https://github.com/JVMartin/jest-fp-ts-broken/blob/master/tsconfig.json#L19

Here is the test:
https://github.com/JVMartin/jest-fp-ts-broken/blob/master/src/main.spec.ts

Result of `npm run test`:
```
> test@0.0.2 test
> npm run test:unit


> test@0.0.2 test:unit
> jest -c jest.unit.config.js

 FAIL  src/main.spec.ts
  ● Test suite failed to run

    src/main.spec.ts:8:18 - error TS2339: Property 'toBeEither' does not exist on type 'JestMatchers<Validation<{ name: string; }>>'.

    8   expect(either).toBeEither();
                       ~~~~~~~~~~

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.255 s
Ran all test suites.
```

**Comment by leilapearson** [comment]
Thanks for the repo. Your configuration does look good so I'm not sure what's going on. So far I've discovered that if I add `import '@relmify/jest-fp-ts';` to your `main.spec.ts` file the test runs successfully.  This shouldn't be required though, and isn't required in my own test package. I'll let you know what I find.

**Comment by leilapearson** [comment]
@JVMartin I still haven't figured out why my test repo works but yours doesn't. I've tried many different configuration options to make your repo more similar to mine and vice versa.

Here's my test repo in case you want to try as well. Maybe you can spot the key difference:

https://github.com/leilapearson/test-jest-fp-ts

**Comment by leilapearson** [comment]
Found the problem. Your global.d.ts file has a typo. It says "remlify" instead of "relmify".  I didn't notice until I copy-pasted over the line with the one from my repo. Once you correct that typo everything should work.

**Comment by JVMartin** [comment]
Yikes, how frustrating that this doesn't appear as an error when building / running! :disappointed: Import statements throw errors in all other contexts in node? Very strange.

Regardless, thank you so much for the guidance.

**Comment by leilapearson** [comment]
Very annoying indeed. eslint didn't catch it either with my previous configuration. I've updated my eslint configuration now per https://www.npmjs.com/package/eslint-import-resolver-typescript so it does detect this error now.
