### ISSUE TITLE
Expect Either.Left error matching string/regex

### ISSUE THREAD

**Issue by kristiannotari** [relmify/jest-fp-ts#8]
**Is your feature request related to a problem? Please describe.**
I'm trying to comfortably express that an Either.Left should be an error with a message string defined as one of the expected values.

**Describe the solution you'd like**
I'd like to have a `.isLeftErrorMatching(string | RegExp)` as jest does with normal strings without having to extract the left error message string from the Either result

**Describe alternatives you've considered**
I can always check if the result is an Either.Left and then access the error message property, but this way I have to use assertions or conditionals during a test, things that in some eslint scenarios are forbidden / discouraged

**Additional context**
I couldn't find a working method to have what I needed with the current exposed matchers, but if you know how to achieve the same thing, I'm open to anything

**Comment by leilapearson** [comment]
Thanks for the feature request @kristiannotari 

Just to be clear, can you confirm that you're looking for a matcher that expects a Left with a standard Javascript/Typescript `Error` object and checks that the string in the `message` property contains the supplied string or matches the supplied regex? 

Seems reasonable and seems like it would be a fairly common scenario. I'll take a look.

**Comment by kristiannotari** [comment]
Yeah I confirm.

The point being I'd like to abstractly think about checking errors with string or regex as I would do with jest, the only thing changing is that I have an `Either<L,R>`.

I don't know if you'd like to strictly type this approach to only works with standard js/ts `Error` since jest usually doesn't do that much strictly, but yeah.

**Comment by leilapearson** [comment]
Perfect. I can't check in the type signature for the matcher but I'll use a type guard inside the matcher so if fails if the received left value is not an instance of `Error`.

**Comment by leilapearson** [comment]
Okay - just looking a bit more at similar matchers to this in `jest` and `jest-extended`.

`jest` has:

[.toThrow(error?)](https://jestjs.io/docs/expect#tothrowerror) 

You can provide an optional argument to test that a specific error is thrown:

regular expression: error message matches the pattern
string: error message includes the substring
error object: error message is equal to the message property of the object
error class: error object is instance of class

With no argument it just checks that the supplied function throws.

That's quite a lot of options for the one argument (not sure that I love that) - and of course you cannot check both the type of the object (error class) and the error message in the same call, so ...


`jest-extended` has: 

[.toThrowWithMessage(type, message)](https://jest-extended.jestcommunity.dev/docs/matchers/function/#tothrowwithmessagetype-message) which requires you to pass both the type of the error and a string or regex to match 

Which interface were you hoping for @kristiannotari? One of these or something different? 

Note that I was thinking to call the matcher `.toBeLeftErrorMatching` or `.toBeLeftError`.  There is already a matcher called `.toBeLeftWithErrorsMatching` but in that case the "Errors" are validation errors from io-ts unrelated to js/ts Error objects.

**Comment by kristiannotari** [comment]
Yeah like the first time I've used this I headed towards using `.toBeLeftWithErrorsMatching` but then realized it was for validation errors from io-ts.

Right now you can check if the result is a left matching the value you passed in or is a left at all. So this already exclude the "check if Error with this message" option, even if you have to construct an error yourself instead of just passing the message string, and the general "toThrow" use case, since if it's a left (functional) equals it throws (non functional).

As long as no one's complaining, I'd rather stick with the simple option of treating the lefts as Error instances and provide a way to check for their messages either by string or regex, so it would be easier to write and read those tests. But I don't know you design goals for this library.

**Comment by leilapearson** [comment]
Added a new `.toBeLeftErrorMatching(string | regExp)` matcher in `v2.1.0`.
