### ISSUE TITLE
TS2305: Module '"@jest/expect-utils"' has no exported member 'TesterContext'.

### ISSUE THREAD

**Issue by TheCrowd** [relmify/jest-fp-ts#9]
**Describe the issue**
Package.json used in my project
```json
    "@relmify/jest-fp-ts": "^2.0.2",
    "@types/jest": "29.0.3",
    "@typescript-eslint/eslint-plugin": "5.40.0",
    "eslint": "8.25.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-config-standard-with-typescript": "23.0.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jest": "27.1.3",
    "eslint-plugin-n": "15.3.0",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-promise": "6.0.1",
    "jest": "^29.0.3",
    "prettier": "2.7.1",
    "ts-jest": "29.0.5",
    "ts-node": "10.9.1",
    "typescript": "4.9.5"
```

**To Reproduce**
Install latest version of jest, when try to build the project, it will throw the error `TS2305: Module '"@jest/expect-utils"' has no exported member 'TesterContext'.`

Remove the  "@relmify/jest-fp-ts": "^2.0.2" fixes the issue.

**Expected behavior**
Project can build successfully

**Suggested fix**
Upgrade the dependency of the project to latest version of jests

**Additional context**
Checking in the yarn-lock.json, the library depends on the follow library:
```
    "@jest/expect-utils" "^28.0.2",
    expect "^28.0.2",
    jest-get-type "^28.0.2",
    jest-matcher-utils "^28.0.2",
```

**Comment by leilapearson** [comment]
@TheCrowd I'm having trouble reproducing this issue. 

My test project builds fine with the following dependencies:
 
``` json
    "@relmify/jest-fp-ts": "^2.0.2",
    "@relmify/jest-serializer-strip-ansi": "^1.0.2",
    "@types/jest": "^29.4.2",
    "@types/node": "^18.15.3",
    "@types/pretty-format": "^24.3.0",
    "@typescript-eslint/eslint-plugin": "^5.55.0",
    "@typescript-eslint/parser": "^5.55.0",
    "eslint": "^8.36.0",
    "eslint-config-prettier": "^8.7.0",
    "eslint-plugin-jest": "^27.2.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-unused-imports": "^2.0.0",
    "jest": "^29.5.0",
    "jest-snapshot-serializer-raw": "^1.2.0",
    "jest-watch-toggle-config": "^2.0.1",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.8.4",
    "pretty-format": "^29.5.0",
    "rimraf": "^4.4.0",
    "ts-jest": "^29.0.5",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5"

```

Using `jest-fp-ts` matchers in jest tests in the same project also works.

Are you still having this issue? 

If so, could you possibly provide a test repo that I could use to reproduce it?

**Comment by leilapearson** [comment]
I wasn't able to reproduce this issue, but I have updated `jest-fp-ts` dependencies to use jest version 29 in `v2.1.0` which has now been released.
